### ISSUE TITLE
request 添加参数

### ISSUE THREAD

**Issue by China-Chenlu** [henix/scetty#3]
只有 body 和header ，建议再添加 parameter吧:
  /**
     * Adds a query parameter with the given name and value.
     * The value is {@link URLEncoder#encode(String, String) UTF-8 URL encoded}.
     *
     * @param name the name of the query parameter
     * @param value the value of the query parameter
     * @return this request object
     */
    Request param(String name, String value);

**Comment by henix** [comment]
请看文档的“GET with URL parameters”部分，可以通过 Url 工具类来构造 url 。

**Comment by China-Chenlu** [comment]
`      Get( 
        url=url,
        headers=headers,
        pams = List("name"->"value")
      )

      Post(
        url = url,
        headers = headers,
        pams =  List("name"->"value"),
        body = StringBody("")
      )
`

`req.pams.foreach(pam=> request.param(pam._1,pam._2))`

感觉这样在添加参数的时候，会更方便些。
就是提个建议吧。

**Comment by henix** [comment]
嗯，我觉得语义上，这个 params 应该是属于 url 的一部分，而并不是直接从属于请求的。所以我认为放 url 里面会更合适。

比如，根据 RFC ，url 的 query 部分可能并不一定是用 x-www-form-urlencoded 编码的，key 和 value 既可以用“=”和“&”连接，也可以用其他自定义的方式连接起来，这种情况下把 params 放在请求里面并不合适。

HttpReq 类应该跟一个 HTTP 请求对应起来，而 HTTP 协议本身并不会关心 url 的参数。

这是我设计时的主要考虑吧，其他库也许会从方便的角度考虑，但我觉得首要的还是语义上必须干净清晰。

另外，这样设计耦合更低一些。如果你不喜欢我提供的 Url 工具类，也可以用其他方式构造 url ，比如 Spring 的 UriComponentsBuilder 。
